<a href="https://colab.research.google.com/github/VishalChoudhari2003/Machine-Learning-Algorithms/blob/main/16_Handling_Date_and_Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [8]:
date=pd.read_csv('/content/orders.csv')
time=pd.read_csv('/content/messages.csv')

In [9]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [10]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [11]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [12]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

##Working with Dates

In [13]:
#Converting to datetime datatype
date['date']=pd.to_datetime(date['date'])
#

In [14]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [16]:
 date['date_year']=date['date'].dt.year
 date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [17]:
date['date_month']=date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [18]:
date['date_day']=date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year  date_month  date_day
0 2019-12-10        5628       25       3       2019          12        10
1 2018-08-15        3646       14     157       2018           8        15
2 2018-10-23        1859       25       1       2018          10        23
3 2019-08-17        7292       25       1       2019           8        17
4 2019-01-06        4344       25       3       2019           1         6

In [19]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2025, 3, 17, 7, 33, 13, 664714)

In [20]:
today - date['date']

0     1924 days 07:33:13.664714
1     2406 days 07:33:13.664714
2     2337 days 07:33:13.664714
3     2039 days 07:33:13.664714
4     2262 days 07:33:13.664714
                 ...
995   2352 days 07:33:13.664714
996   2293 days 07:33:13.664714
997   2141 days 07:33:13.664714
998   2206 days 07:33:13.664714
999   1980 days 07:33:13.664714
Name: date, Length: 1000, dtype: timedelta64[ns]

In [21]:
(today - date['date']).dt.days

0      1924
1      2406
2      2337
3      2039
4      2262
       ...
995    2352
996    2293
997    2141
998    2206
999    1980
Name: date, Length: 1000, dtype: int64

In [23]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [24]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [25]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [26]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [27]:
today - time['date']

0     4110 days 06:43:13.664714
1     3974 days 07:53:13.664714
2     4460 days 07:12:13.664714
3     3762 days 07:02:13.664714
4     4159 days 08:22:13.664714
                 ...
995   4749 days 06:43:13.664714
996   4070 days 08:19:13.664714
997   4535 days 07:56:13.664714
998   4651 days 07:59:13.664714
999   3923 days 08:08:13.664714
Name: date, Length: 1000, dtype: timedelta64[ns]

In [28]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.551282e+08
1      3.433820e+08
2      3.853699e+08
3      3.250621e+08
4      3.593677e+08
           ...
995    4.103378e+08
996    3.516780e+08
997    3.918526e+08
998    4.018752e+08
999    3.389765e+08
Name: date, Length: 1000, dtype: float64

In [29]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      5.918803e+06
1      5.723033e+06
2      6.422832e+06
3      5.417702e+06
4      5.989462e+06
           ...
995    6.838963e+06
996    5.861299e+06
997    6.530876e+06
998    6.697919e+06
999    5.649608e+06
Name: date, Length: 1000, dtype: float64

In [30]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0       98646.720462
1       95383.887129
2      107047.203796
3       90295.037129
4       99824.370462
           ...
995    113982.720462
996     97688.320462
997    108847.937129
998    111631.987129
999     94160.137129
Name: date, Length: 1000, dtype: float64